export const SLIDERS = [
  {
    img: "/img/BANNER-WEB-INSTITUCIONAL-BIG PONS.png",
    alt: "Banner",
  },
  {
    img: "/img/banner-takeaway.png",
    alt: "TakeAway",
  },
];
export const BURGERS = [
  {
    img: "/img/BigPonsSimple.jpg",
    alt: "Big Pons Simple + Papas",
    name: "Big Pons Simple + Papas Fritas",
    desc: "Medallon x1 Cheddar Fetas x2 Bacon Cebolla Crispy Aderezo Big Pons",
    price: "$ 2.400",
    link: "../../product/a",
  },
  {
    img: "/img/SweetOnionSimple.jpeg",
    alt: "Sweet Onion Simple + Papas Fritas",
    name: "Sweet Onion Simple + Papas Fritas",
    desc: "Medallon x1 Cheddar Fetas x2 Bacon Cebolla Caramelizada",
    price: "$ 2.400",
    link: "../../product/b",
  },

  {
    img: "/img/CheseBurgerSimple.jpeg",
    alt: "Cheese Burger Simple + Papas Fritas",
    name: "Cheese Burger Simple + Papas Fritas",
    desc: "Medallon x1 Cheddar Feta x2",
    price: "$ 1.950",
    link: "../../product/c",
  },
  {
    img: "/img/AmericanBurgerSimple.jpeg",
    alt: "American Burger Simple + Papas Fritas",
    name: "American Burger Simple + Papas Fritas",
    desc: "Medallon x 1 Cheddar Fetas x2 Tomate Lechuga Cebolla Cruda Dill Pickles Aderezo Thousand Island",
    price: "$ 2.350",
    link: "../../product/d",
  },
  {
    img: "/img/GrilledOnion.jpeg",
    alt: "Grilled Onion + Papas Fritas",
    name: "Grilled Onion + Papas Fritas",
    desc: "Medallon x2 Cheddar x4 Cebolla Grilled",
    price: "$ 2.550",
  },
  {
    img: "/img/RoyalSimple.jpg",
    alt: "Royal Simple + Papas Fritas",
    name: "Royal Simple + Papas Fritas",
    desc: "Medallon x1 Cheddar Fetas x2 Cebolla Cruda Ketchup Mostaza Pepino",
    price: "$ 2.150",
  },
  {
    img: "/img/CaliforniaSimple.jpeg",
    alt: "California simple + Papas fritas",
    name: "California simple + Papas fritas",
    desc: "Medallón, cheddar x2, lechuga, tomate, cebolla, doble california sauce y papas fritas",
    price: "$ 2.350",
  },
  {
    img: "/img/StackedBacon.jpg",
    alt: "Stacked Bacon Simple + Papas Fritas",
    name: "Stacked Bacon Simple + Papas Fritas",
    desc: "Medallón de x 1 + Cheddar fetas x 2 + Bacon ahumado por nosotros x 4 fetas + Relish sauce + Papas fritas",
    price: "$ 2.600",
  },
  {
    img: "/img/SweetSpicy.jpg",
    alt: "Sweet ´n´ Spicy Simple + Papas fritas",
    name: "Sweet ´n´ Spicy Simple + Papas fritas",
    desc: "Medallon x 1 + Cheddar fetas x 2 + Mermelada de Tomate + Pickles de Pepino + Alioli de Jalapeños + Papas Fritas",
    price: "$ 2.150",
  },
  {
    img: "/img/PestoSimple.jpg",
    alt: "Pesto Simple + Papas fritas",
    name: "Pesto Simple + Papas fritas",
    desc: "Medallon x 1 + Cheddar fetas x 2 + Tomate + Pesto + Alioli + Papas fritas",
    price: "$ 2.150",
  },
  {
    img: "/img/BaconBacon.jpeg",
    alt: "Bacon & Bacon Simple + Papas Fritas",
    name: "Bacon & Bacon Simple + Papas Fritas",
    desc: "Medallon x1 Cheddar Fetas x2 Black Pepper Maple Bacon Dill Pickles Baconnaise Sauce",
    price: "$ 2.400",
  },
  {
    img: "/img/Veggie.jpeg",
    alt: "Meatfree Burger 0% Carne + Papas Fritas",
    name: "Meatfree Burger 0% Carne + Papas Fritas",
    desc: "Medallon Plant Based x1 , Cheddar Fetas x2, Pickles de Pepino, Cebolla, Tomate, Lechuga, Mayonesa, Ketchup, Papas fritas",
    price: "$ 2.100",
  },
];
export const STARTERS = [
  {
    img: "/img/papasfritas.jpeg",
    alt: "Papas Fritas",
    name: "Papas Fritas",
    desc: "Papas Fritas",
    price: "$ 850",
  },
  {
    img: "/img/papaschedaryverdeo.jpeg",
    alt: "Papas Cheddar y Verdeo",
    name: "Papas Cheddar y Verdeo",
    desc: "Papas Cheddar y Verdeo",
    price: "$ 1.190",
  },
  {
    img: "/img/papaschedarybacon.jpeg",
    alt: "Papas Fritas Cheddar Bacon",
    name: "Papas Fritas Cheddar Bacon",
    desc: "Papas Fritas Cheddar Bacon",
    price: "$ 1.490",
  },
  {
    img: "/img/aros.jpeg",
    alt: "Aros de Cebolla + BBQ",
    name: "Aros de Cebolla + BBQ",
    desc: "300grs de Aros de Cebolla + BBQ Casera",
    price: "$ 1.490",
  },
  {
    img: "/img/bastones.jpeg",
    alt: "Bastones de Mozzarella",
    name: "Bastones de Mozzarella",
    desc: "12 Bastones de muzzarella + Salsa Marinara",
    price: "$ 1.490",
  },
  {
    img: "/img/nuggetsx10.jpeg",
    alt: "Nuggets de Pollo x10",
    name: "Nuggets de Pollo x10",
    desc: "Nuggets de Pollo x10 Dip Ketchup Dip Salsa Ranch",
    price: "$ 990",
  },
  {
    img: "/img/nuggetsx10.jpeg",
    alt: "Nuggets de Pollo x20",
    name: "Nuggets de Pollo x20",
    desc: "Nuggets de Pollo x20 Dip Ketchup Dip Salsa Ranch",
    price: "$ 1.390",
  },
];

export const BEBIDAS = [
  {
    img: "/img/pepsi.png",
    alt: "Pepsi Regular 345ml",
    name: "Pepsi Regular 345ml",
    desc: "Pepsi Regular 345ml ",
    price: "$ 400",
  },
  {
    img: "/img/pepsiblack.png",
    alt: "Pepsi Black 345ml",
    name: "Pepsi Black 345ml",
    desc: "Pepsi Black 345ml ",
    price: "$ 400",
  },
  {
    img: "/img/sevenup.png",
    alt: "Seven Up Regular 345ml",
    name: "Seven Up Regular 345ml",
    desc: "Seven Up Regular 345ml ",
    price: "$ 400",
  },
  {
    img: "/img/sevenupfree.png",
    alt: "Seven Up Free 345ml",
    name: "Seven Up Free 345ml",
    desc: "Seven Up Free 345ml ",
    price: "$ 400",
  },
  {
    img: "/img/agua.png",
    alt: "Agua Mineral Sin Gas Eco de los Andes",
    name: "Agua Mineral Sin Gas Eco de los Andes",
    desc: "Agua Mineral Sin Gas Eco de los Andes ",
    price: "$ 450",
  },
  {
    img: "/img/247.png",
    alt: "Cerveza Patagonia 24.7 410ml",
    name: "Cerveza Patagonia 24.7 410ml",
    desc: "Cerveza Patagonia 24.7 410ml ",
    price: "$ 600",
  },
  {
    img: "/img/bohemian.png",
    alt: "Cerveza Patagonia Bohemian 410ml",
    name: "Cerveza Patagonia Bohemian 410ml",
    desc: "Cerveza Patagonia Bohemian 410ml ",
    price: "$ 600",
  },
  {
    img: "/img/amber.png",
    alt: "Cerveza Patagonia Amber Lager 410ml",
    name: "Cerveza Patagonia Amber Lager 410ml",
    desc: "Cerveza Patagonia Amber Lager 410ml ",
    price: "$ 600",
  },
];
